global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'skillscan-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8081

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - skillscan_prometheus:9090